# Generated by Django 6.0.7 on 2026-07-17 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='الرقم الأكاديمي')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='رقم هاتف ولي الأمر (بصيغة دولية)')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='المادة الدراسية')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, max_length=5, verbose_name='الدرجة')),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, max_length=5, verbose_name='الدرجة الكبرى')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='whatsapp_app.student', verbose_name='الطالب')),
            ],
        ),
    ]
